# Generated by Django 4.0.6 on 2022-07-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemania', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(default='icon.jpg', upload_to='profiles'),
        ),
    ]
