# Generated by Django 4.0.6 on 2022-07-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemania', '0002_signup_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='user_gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], max_length=15),
        ),
    ]
